### ISSUE TITLE
Crashes on using certain input values.

### ISSUE THREAD

**Issue by JJPPeters** [ADyson/clTEM#9] opened 2014-05-13 12:47 UTC
Using certain range of values causes the program to crash e.g.small aperture sizes. Possible from trying to normalise an array of zeros?

**Comment by ADyson** [comment] 2014-07-22 16:56
Some of this has been fixed by detecting if there is zero image contrast. The cause of the other crashes has been identified and this isssue is moved to #83.

**Closed as completed by ADyson** 2014-07-22 16:56 UTC
Labels: bug
